# Generated by Django 4.0.3 on 2022-07-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=240, null=True)),
                ('movieurl', models.CharField(max_length=2400, null=True)),
                ('movieposter', models.FileField(blank=True, null=True, upload_to='images/')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netflix.user_registration')),
            ],
        ),
    ]
